export const BOARD_DATA = [
    { name: "GO", type: "go", color: null, price: 0 },
    { name: "Old Kent Road", type: "property", color: "#955436", price: 60 },
    { name: "Community Chest", type: "community-chest", color: null, price: 0 },
    { name: "Whitechapel Road", type: "property", color: "#955436", price: 60 },
    { name: "Income Tax", type: "tax", color: null, price: 200 },
    { name: "Kings Cross Station", type: "station", color: "#000000", price: 200 },
    { name: "The Angel Islington", type: "property", color: "#aae0fa", price: 100 },
    { name: "Chance", type: "chance", color: null, price: 0 },
    { name: "Euston Road", type: "property", color: "#aae0fa", price: 100 },
    { name: "Pentonville Road", type: "property", color: "#aae0fa", price: 120 },
    { name: "Jail", type: "jail", color: null, price: 0 },
    { name: "Pall Mall", type: "property", color: "#d93a96", price: 140 },
    { name: "Electric Company", type: "utility", color: "#ffffff", price: 150 },
    { name: "Whitehall", type: "property", color: "#d93a96", price: 140 },
    { name: "Northumberland Avenue", type: "property", color: "#d93a96", price: 160 },
    { name: "Marylebone Station", type: "station", color: "#000000", price: 200 },
    { name: "Bow Street", type: "property", color: "#f7941d", price: 180 },
    { name: "Community Chest", type: "community-chest", color: null, price: 0 },
    { name: "Marlborough Street", type: "property", color: "#f7941d", price: 180 },
    { name: "Vine Street", type: "property", color: "#f7941d", price: 200 },
    { name: "Free Parking", type: "free-parking", color: null, price: 0 },
    { name: "Strand", type: "property", color: "#ed1c24", price: 220 },
    { name: "Chance", type: "chance", color: null, price: 0 },
    { name: "Fleet Street", type: "property", color: "#ed1c24", price: 220 },
    { name: "Trafalgar Square", type: "property", color: "#ed1c24", price: 240 },
    { name: "Fenchurch St Station", type: "station", color: "#000000", price: 200 },
    { name: "Leicester Square", type: "property", color: "#fef200", price: 260 },
    { name: "Coventry Street", type: "property", color: "#fef200", price: 260 },
    { name: "Water Works", type: "utility", color: "#ffffff", price: 150 },
    { name: "Piccadilly", type: "property", color: "#fef200", price: 280 },
    { name: "Go To Jail", type: "go-to-jail", color: null, price: 0 },
    { name: "Regent Street", type: "property", color: "#1fb25a", price: 300 },
    { name: "Oxford Street", type: "property", color: "#1fb25a", price: 300 },
    { name: "Community Chest", type: "community-chest", color: null, price: 0 },
    { name: "Bond Street", type: "property", color: "#1fb25a", price: 320 },
    { name: "Liverpool St Station", type: "station", color: "#000000", price: 200 },
    { name: "Chance", type: "chance", color: null, price: 0 },
    { name: "Park Lane", type: "property", color: "#0072bb", price: 350 },
    { name: "Super Tax", type: "tax", color: null, price: 100 },
    { name: "Mayfair", type: "property", color: "#0072bb", price: 400 },
];
